name: hivpn
description: "HiVPN Android MVP"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  google_mobile_ads: ^5.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.0
  tutorial_coach_mark: 1.2.11
  cryptography: ^2.7.0
  dio: ^5.4.0
  google_fonts: ^6.1.0
  equatable: ^2.0.7
#  characters: ^1.4.0
  http: ^1.2.1
  web_socket_channel: ^2.4.0
  csv: ^5.0.2
  flutter_speed_test_plus: ^1.0.10
  openvpn_flutter: ^1.3.4
  flutter_local_notifications: ^17.1.2
  flutter_svg: ^2.0.9
  file_picker: ^8.0.3
  app_settings: ^5.1.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/reference/
    - assets/CountryFlags/
    - assets/

flutter_launcher_icons:
      android: "launcher_icon"
      ios: true
      image_path: "assets/icons/appicon.png"
      # run -> flutter pub run flutter_launcher_icons:main
      # Optional: Add configurations for other platforms like web, windows, macos
      # web:
      #   generate: true
      #   image_path: "assets/icons/app_icon.png"
      # windows:
      #   generate: true
      #   image_path: "assets/icons/app_icon.png"
      #   icon_size: 48 # Example size